### ISSUE TITLE
avr_local does not compile with sloeber43

### ISSUE THREAD

**Issue by jml3on** [jantje/hardware#13]
steps:

- clean install, new workspace (windows 10)
- create simple blink project
- import github's hardware project.
- add the private platform
- create Debug config using avr_local
- activate Debug config
- compile

Note: I had to first define the runtime.tools.mingw.path environment variable to avoid an invalid make rule.

'Building file: C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.cpp'
'Starting C++ compile'
"C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++" -c -g -O0 -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR_LOCAL   -DLOCAL_RUN   -I"C:\github\hardware\jantje\avr_local\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard" -MMD -MP -MF"core\core\Arduino.cpp.d" -MT"core\core\Arduino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.cpp"  -o  "core\core\Arduino.cpp.o"   -Dsrandom=srand -Drandom=rand
In file included from C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.h:9,
                 from C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.cpp:2:
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:46:22: error: lvalue required as unary '&' operand
 #define DDRB    (0x04)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:129:14: note: in expansion of macro 'DDRB'
  (uint16_t) &DDRB,
              ^~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:76:22: error: lvalue required as unary '&' operand
 #define DDRC    (0x07)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:130:14: note: in expansion of macro 'DDRC'
  (uint16_t) &DDRC,
              ^~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:106:22: error: lvalue required as unary '&' operand
 #define DDRD    (0x0A)

**Comment by jml3on** [comment]
Forgot to mention that I see the same problem with 4.2

But in 4.2, if I use the pc/1.0.2 platform (which apprently is no longer in 4.3), it compiles fine.

pc/1.0.2 also works fine in 4.3

**Comment by jantje** [comment]
@jml3on 
This is all very confusing to me. I tried here and it works
What is confusing?
>....pc/1.0.2 platform (which apprently is no longer in 4.3)...

versus
>pc/1.0.2 also works fine in 4.3

if you use pc/1.0.2 then why do you do
>import github's hardware project.
>add the private platform

When using pc/1.0.2 this is not needed
>Note: I had to first define the runtime.tools.mingw.path environment variable to avoid an invalid make rule.

**Comment by jml3on** [comment]
Sorry if I wasn't clear.

Before yesterday, I was using 4.2 with pc/1.0.2 and I had no problem.
Yesterday, I was prompted to upgrade to 4.3, which I did and I started seeing this.

While trying to debug what caused the issue, I've tried all 4 combinations of platform (pc/1.0.2, avr_local) and sloeber version (4.2, 4.3). The pc/1.0.2 options works in both version of sloeber; the avr_local in none.

I'm happy to focus on 4.3/avr_local, since that the one that should be working.

adding a screenshot of my setup:

![image](https://user-images.githubusercontent.com/5844503/43969022-af622f10-9c7d-11e8-9705-7f1c94d864de.png)

**Comment by jml3on** [comment]
also tried with the exact wingw version you had in the video and still seeing the same problem, so it doesn't look like it's a compiler version issue.
```
09:43:11 **** Incremental Build of configuration Debug for project blink ****
"C:\\sloeber\\arduinoPlugin\\tools\\make\\make" all 
'Building file: C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.cpp'
'Starting C++ compile'
"C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32/bin/g++" -c -g -O0 -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR_LOCAL   -DLOCAL_RUN   -I"C:\github\hardware\jantje\avr_local\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard" -MMD -MP -MF"core\core\Arduino.cpp.d" -MT"core\core\Arduino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.cpp"  -o  "core\core\Arduino.cpp.o"   -Dsrandom=srand -Drandom=rand
In file included from C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.h:9:0,
                 from C:\github\hardware\jantje\avr_local\cores\arduino\Arduino.cpp:2:
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:46:22: error: lvalue required as unary '&' operand
 #define DDRB    (0x04)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:129:14: note: in expansion of macro 'DDRB'
  (uint16_t) &DDRB,
              ^~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:76:22: error: lvalue required as unary '&' operand
 #define DDRC    (0x07)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:130:14: note: in expansion of macro 'DDRC'
  (uint16_t) &DDRC,
              ^~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:106:22: error: lvalue required as unary '&' operand
 #define DDRD    (0x0A)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:131:14: note: in expansion of macro 'DDRD'
  (uint16_t) &DDRD,
              ^~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:56:22: error: lvalue required as unary '&' operand
 #define PORTB   (0x05)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:137:14: note: in expansion of macro 'PORTB'
  (uint16_t) &PORTB,
              ^~~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:86:22: error: lvalue required as unary '&' operand
 #define PORTC   (0x08)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:138:14: note: in expansion of macro 'PORTC'
  (uint16_t) &PORTC,
              ^~~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:116:22: error: lvalue required as unary '&' operand
 #define PORTD   (0x0B)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:139:14: note: in expansion of macro 'PORTD'
  (uint16_t) &PORTD,
              ^~~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:36:22: error: lvalue required as unary '&' operand
 #define PINB    (0X03)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:145:14: note: in expansion of macro 'PINB'
  (uint16_t) &PINB,
              ^~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:66:22: error: lvalue required as unary '&' operand
 #define PINC    (0x06)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:146:14: note: in expansion of macro 'PINC'
  (uint16_t) &PINC,
              ^~~~
C:\github\hardware\jantje\avr_local\cores\arduino\defines.h:96:22: error: lvalue required as unary '&' operand
 #define PIND    (0x09)
                      ^
C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.21\variants\standard/pins_arduino.h:147:14: note: in expansion of macro 'PIND'
  (uint16_t) &PIND,
              ^~~~
core\core\subdir.mk:36: recipe for target 'core\core\Arduino.cpp.o' failed
make: *** [core\core\Arduino.cpp.o] Error 1

09:43:12 Build Failed. 11 errors, 0 warnings. (took 481ms)
```

**Comment by jml3on** [comment]
well, finally figured out what was wrong.

I was following the instructions from the 'Debug your arduino code on your local machine' video and apparently, not only the installation of the jantje platform boards are no longer required, but they simply don't work.

I would suggest to delete, or truncate that video, so others don't waste hours banging their heads like I did. Also, maybe, add a note on the jantje/hardware github page explaining that it is bundled in sloeber.

On the plus side, it's now all bundled in sloeber, which is awesome!

Thanks.

**Comment by jantje** [comment]
>I would suggest to delete, or truncate that video, so others don't waste hours banging their heads like I did.

In the old days you could add text to youtube video's. This feature got disabled and I don't know a alternative.
If you do please advice.

**Comment by jantje** [comment]
> don't waste hours banging their heads like I did. 

on the plus side. I spend weeks getting this to work and then spend days to make it easy for others. So a couple of hours .....

**Comment by jml3on** [comment]
yeah, no worries, it was totally worth it, as I can now write unit tests. Yay!

As the video owner, you can pin a comment at the top that will be easily visible by everyone. Other option is the add to the description, but the description gets folded. I think the comment is more visible.

**Comment by jantje** [comment]
>As the video owner, you can pin a comment at the top that will be easily visible by everyone. Other option is the add to the description, but the description gets folded. I think the comment is more visible.

I used to be able to do this but I don't know how to do this after the many improvements youtube made :-(
If you have a video explaining how to do this that is still valid, give me the link. There are a couple of video's of mine that need some "update info"
